-- Deaf Registry and Monitoring System - PostgreSQL (Supabase) schema
-- Translated from the original MySQL schema.sql. Key differences from that version:
--   * id columns use GENERATED BY DEFAULT AS IDENTITY (not ALWAYS) so the one-off
--     data migration script can insert explicit legacy ids from the MySQL database.
--   * ENUM columns become VARCHAR + CHECK constraints (easier to alter later than
--     native Postgres enum types — this project has already extended enum-like
--     columns, e.g. marital_status, more than once).
--   * TINYINT(1) booleans become native BOOLEAN.
--   * DATETIME becomes TIMESTAMP.
--   * MySQL's "ON UPDATE CURRENT_TIMESTAMP" has no direct equivalent — handled via
--     a shared trigger function (set_updated_at) applied per table below.

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS municipalities (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DROP TRIGGER IF EXISTS trg_municipalities_updated_at ON municipalities;
CREATE TRIGGER trg_municipalities_updated_at BEFORE UPDATE ON municipalities
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS barangays (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  municipality_id INT NOT NULL REFERENCES municipalities(id) ON DELETE CASCADE,
  name VARCHAR(150) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_barangay UNIQUE (municipality_id, name)
);
DROP TRIGGER IF EXISTS trg_barangays_updated_at ON barangays;
CREATE TRIGGER trg_barangays_updated_at BEFORE UPDATE ON barangays
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS teachers (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  contact_number VARCHAR(30) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DROP TRIGGER IF EXISTS trg_teachers_updated_at ON teachers;
CREATE TRIGGER trg_teachers_updated_at BEFORE UPDATE ON teachers
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  username VARCHAR(50) NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'conductor' CHECK (role IN ('admin','conductor','super_admin')),
  teacher_id INT NULL REFERENCES teachers(id) ON DELETE SET NULL,
  photo_url VARCHAR(255) NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  -- Self-service signup gating: admin-created accounts (via Manage Users) are created
  -- already approved; only the public /auth/signup path starts as 'pending'. Email
  -- verification was dropped (would need a paid/verified sending domain) - approval alone
  -- gates login now.
  email_verified BOOLEAN NOT NULL DEFAULT true,
  email_verification_token VARCHAR(64) NULL,
  email_verification_expires TIMESTAMP NULL,
  approval_status VARCHAR(20) NOT NULL DEFAULT 'approved' CHECK (approval_status IN ('pending','approved','rejected')),
  contact_number VARCHAR(30) NULL,
  location VARCHAR(255) NULL,
  shared_latitude DOUBLE PRECISION NULL,
  shared_longitude DOUBLE PRECISION NULL,
  shared_location_at TIMESTAMP NULL,
  last_login_at TIMESTAMP NULL,
  last_seen_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS deaf_individuals (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid VARCHAR(36) NOT NULL UNIQUE,
  full_name VARCHAR(190) NOT NULL,
  photo_url VARCHAR(255) NULL,
  age INT NULL,
  birth_date DATE NULL,
  gender VARCHAR(10) NOT NULL CHECK (gender IN ('Male','Female','Other')),
  barangay_id INT NOT NULL REFERENCES barangays(id),
  purok VARCHAR(100) NULL,
  municipality_id INT NOT NULL REFERENCES municipalities(id),
  latitude DOUBLE PRECISION NULL,
  longitude DOUBLE PRECISION NULL,
  skill_level VARCHAR(20) NOT NULL DEFAULT 'Natural' CHECK (skill_level IN ('Skilled','Semi-skilled','Natural')),
  monitoring_status VARCHAR(20) NOT NULL DEFAULT 'Unlocated' CHECK (monitoring_status IN ('RV','BS','Transferred','Unlocated')),
  assigned_teacher_id INT NULL REFERENCES teachers(id) ON DELETE SET NULL,
  assigned_date DATE NULL,
  contact_number VARCHAR(30) NULL,
  email VARCHAR(190) NULL,
  marital_status VARCHAR(20) NULL CHECK (marital_status IS NULL OR marital_status IN ('Single','Married','Widowed','Separated','Divorced')),
  emergency_contact_name VARCHAR(150) NULL,
  emergency_contact_number VARCHAR(30) NULL,
  notes TEXT NULL,
  is_deleted BOOLEAN NOT NULL DEFAULT false,
  created_by INT NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DROP TRIGGER IF EXISTS trg_deaf_individuals_updated_at ON deaf_individuals;
CREATE TRIGGER trg_deaf_individuals_updated_at BEFORE UPDATE ON deaf_individuals
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX IF NOT EXISTS idx_deaf_updated_at ON deaf_individuals (updated_at);
CREATE INDEX IF NOT EXISTS idx_deaf_municipality ON deaf_individuals (municipality_id);
CREATE INDEX IF NOT EXISTS idx_deaf_name ON deaf_individuals (full_name);

CREATE TABLE IF NOT EXISTS visits (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid VARCHAR(36) NOT NULL UNIQUE,
  deaf_individual_id INT NOT NULL REFERENCES deaf_individuals(id) ON DELETE CASCADE,
  visit_datetime TIMESTAMP NOT NULL,
  latitude DOUBLE PRECISION NULL,
  longitude DOUBLE PRECISION NULL,
  conductor_id INT NULL REFERENCES teachers(id) ON DELETE SET NULL,
  conductor_name VARCHAR(150) NULL,
  created_by INT NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DROP TRIGGER IF EXISTS trg_visits_updated_at ON visits;
CREATE TRIGGER trg_visits_updated_at BEFORE UPDATE ON visits
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX IF NOT EXISTS idx_visit_deaf ON visits (deaf_individual_id);
CREATE INDEX IF NOT EXISTS idx_visit_updated_at ON visits (updated_at);

CREATE TABLE IF NOT EXISTS remarks (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid VARCHAR(36) NOT NULL UNIQUE,
  visit_id INT NOT NULL REFERENCES visits(id) ON DELETE CASCADE,
  user_id INT NULL REFERENCES users(id) ON DELETE SET NULL,
  user_name VARCHAR(150) NULL,
  remark_text TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DROP TRIGGER IF EXISTS trg_remarks_updated_at ON remarks;
CREATE TRIGGER trg_remarks_updated_at BEFORE UPDATE ON remarks
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX IF NOT EXISTS idx_remark_visit ON remarks (visit_id);
CREATE INDEX IF NOT EXISTS idx_remark_updated_at ON remarks (updated_at);

CREATE TABLE IF NOT EXISTS user_devices (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_id VARCHAR(100) NOT NULL,
  device_label VARCHAR(150) NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('approved','pending','rejected')),
  approved_by INT NULL REFERENCES users(id) ON DELETE SET NULL,
  approved_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_user_device UNIQUE (user_id, device_id)
);

CREATE TABLE IF NOT EXISTS password_reset_requests (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  note VARCHAR(500) NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','resolved')),
  requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at TIMESTAMP NULL,
  resolved_by INT NULL REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_password_reset_status ON password_reset_requests (status, requested_at);

CREATE TABLE IF NOT EXISTS teacher_assignment_history (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deaf_individual_id INT NOT NULL REFERENCES deaf_individuals(id) ON DELETE CASCADE,
  old_teacher_id INT NULL REFERENCES teachers(id) ON DELETE SET NULL,
  new_teacher_id INT NULL REFERENCES teachers(id) ON DELETE SET NULL,
  changed_by INT NULL REFERENCES users(id) ON DELETE SET NULL,
  reason VARCHAR(255) NULL,
  changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_tah_deaf ON teacher_assignment_history (deaf_individual_id, changed_at);

CREATE TABLE IF NOT EXISTS settings (
  "key" VARCHAR(100) NOT NULL PRIMARY KEY,
  "value" VARCHAR(255) NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DROP TRIGGER IF EXISTS trg_settings_updated_at ON settings;
CREATE TRIGGER trg_settings_updated_at BEFORE UPDATE ON settings
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

INSERT INTO settings ("key", "value") VALUES ('overdue_visit_days', '30')
  ON CONFLICT ("key") DO NOTHING;

CREATE TABLE IF NOT EXISTS calendar_events (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(190) NOT NULL,
  description TEXT NULL,
  event_date DATE NOT NULL,
  created_by INT NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DROP TRIGGER IF EXISTS trg_calendar_events_updated_at ON calendar_events;
CREATE TRIGGER trg_calendar_events_updated_at BEFORE UPDATE ON calendar_events
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX IF NOT EXISTS idx_calendar_events_date ON calendar_events (event_date);

CREATE TABLE IF NOT EXISTS audit_logs (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT NULL REFERENCES users(id) ON DELETE SET NULL,
  action VARCHAR(50) NOT NULL,
  entity_type VARCHAR(50) NOT NULL,
  entity_id INT NULL,
  details TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Chat module: temporary, admin-scheduled group chat sessions -------------

-- A recurring template ("every Mon/Wed/Fri, 8:00-9:00 AM") that chatScheduler.js's
-- generateScheduledSessions() turns into a real chat_sessions row each day it's due, so an
-- admin/super_admin sets this up once instead of creating the same session every time.
CREATE TABLE IF NOT EXISTS chat_recurring_schedules (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_name VARCHAR(150) NOT NULL,
  description VARCHAR(500) NULL,
  -- 0=Sunday..6=Saturday, matching Postgres's EXTRACT(DOW FROM ...) - at least one day required.
  days_of_week INT[] NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  retention_policy VARCHAR(20) NOT NULL DEFAULT 'immediate' CHECK (retention_policy IN ('immediate','24h','7d')),
  is_active BOOLEAN NOT NULL DEFAULT true,
  -- The Manila-local calendar date a session was last auto-generated for - prevents generating a
  -- second session for the same day if the scheduler tick runs more than once while still due.
  last_generated_date DATE NULL,
  created_by INT NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- A one-off exception for a single calendar date ("just this Monday, 10 AM-4 PM instead of the
-- usual recurring window") - at most one per schedule_date (UNIQUE), and when active it takes
-- priority over whatever a recurring schedule would otherwise generate that day (see
-- chatScheduler.js::generateScheduledSessions). is_active=false means it's saved on file but
-- deliberately not in effect - the "Keep Recurring Schedule" choice when an admin's single-time
-- save conflicted with an existing recurring schedule for that weekday.
CREATE TABLE IF NOT EXISTS chat_single_schedules (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_name VARCHAR(150) NOT NULL,
  schedule_date DATE NOT NULL UNIQUE,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  remarks VARCHAR(500) NULL,
  retention_policy VARCHAR(20) NOT NULL DEFAULT 'immediate' CHECK (retention_policy IN ('immediate','24h','7d')),
  is_active BOOLEAN NOT NULL DEFAULT true,
  -- 'scheduled' until its date passes, then the scheduler flips it to 'completed' (archived, kept
  -- for audit history rather than deleted) - never 'cancelled' automatically, only via admin delete.
  status VARCHAR(20) NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled','completed','cancelled')),
  created_by INT NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_sessions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_name VARCHAR(150) NOT NULL,
  description VARCHAR(500) NULL,
  start_datetime TIMESTAMP NOT NULL,
  end_datetime TIMESTAMP NOT NULL,
  -- 'scheduled' (before start) -> 'open' (auto, at start time, or admin can open early) ->
  -- 'closed' (admin closed early - can be re-opened while still before end_datetime) ->
  -- 'expired' (auto, at end time or admin delete-via-expiry - terminal, chatScheduler.js cleans up).
  status VARCHAR(20) NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled','open','closed','expired')),
  -- How long expired messages are kept before chatScheduler.js purges them - 'immediate' means
  -- deleted the moment the session expires, matching the primary spec; 24h/7d is the "recommended
  -- enhancement" retention window, admin-configurable per session at creation time.
  retention_policy VARCHAR(20) NOT NULL DEFAULT 'immediate' CHECK (retention_policy IN ('immediate','24h','7d')),
  five_min_warning_sent BOOLEAN NOT NULL DEFAULT false,
  expired_at TIMESTAMP NULL,
  purge_at TIMESTAMP NULL,
  messages_purged BOOLEAN NOT NULL DEFAULT false,
  created_by INT NULL REFERENCES users(id) ON DELETE SET NULL,
  -- Set only for sessions the scheduler auto-generated from a recurring schedule - null for
  -- one-off sessions an admin created directly. ON DELETE SET NULL so deleting the recurring
  -- schedule later doesn't retroactively orphan/delete sessions it already generated.
  recurring_schedule_id INT NULL REFERENCES chat_recurring_schedules(id) ON DELETE SET NULL,
  -- Set only for sessions generated from a single-time schedule - mutually exclusive with
  -- recurring_schedule_id in practice (the scheduler never generates both for the same day).
  single_schedule_id INT NULL REFERENCES chat_single_schedules(id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_chat_sessions_status ON chat_sessions (status, end_datetime);

CREATE TABLE IF NOT EXISTS chat_messages (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INT NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  message VARCHAR(2000) NOT NULL,
  sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  edited_at TIMESTAMP NULL,
  is_deleted BOOLEAN NOT NULL DEFAULT false,
  is_pinned BOOLEAN NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS idx_chat_messages_session ON chat_messages (session_id, id);

CREATE TABLE IF NOT EXISTS chat_participants (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INT NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  left_at TIMESTAMP NULL,
  -- Refreshed by the app's periodic heartbeat while the Chat Room screen is open - drives the
  -- Online/Offline status shown in the participant list (see chat.controller.js::listParticipants).
  last_active_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_muted BOOLEAN NOT NULL DEFAULT false,
  is_removed BOOLEAN NOT NULL DEFAULT false,
  CONSTRAINT uq_chat_participant UNIQUE (session_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_chat_participants_session ON chat_participants (session_id);

CREATE TABLE IF NOT EXISTS chat_notifications (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  session_id INT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
  message VARCHAR(255) NOT NULL,
  sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(20) NOT NULL DEFAULT 'unread' CHECK (status IN ('unread','read'))
);
CREATE INDEX IF NOT EXISTS idx_chat_notifications_user ON chat_notifications (user_id, status);
