-- Deaf Registry and Monitoring System - MySQL (Hostinger) schema
-- Translated from the Postgres/Supabase schema (schema.pg.sql), which is the
-- up-to-date source of truth. Key differences from that version:
--   * id columns use AUTO_INCREMENT instead of GENERATED BY DEFAULT AS IDENTITY.
--   * Foreign keys use explicit CONSTRAINT ... FOREIGN KEY (MySQL requires this
--     form for the constraint to actually be enforced).
--   * updated_at uses MySQL's native ON UPDATE CURRENT_TIMESTAMP instead of a
--     trigger function (schema.pg.sql's set_updated_at()).
--   * TIMESTAMP columns become DATETIME (avoids MySQL's TIMESTAMP auto
--     timezone-conversion behavior).
--   * The one Postgres array column (chat_recurring_schedules.days_of_week
--     INT[]) becomes JSON.
--   * Indexes are declared inline in each CREATE TABLE (MySQL versions before
--     8.0.23 don't support CREATE INDEX IF NOT EXISTS).

CREATE TABLE IF NOT EXISTS municipalities (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS barangays (
  id INT AUTO_INCREMENT PRIMARY KEY,
  municipality_id INT NOT NULL,
  name VARCHAR(150) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_barangay_municipality FOREIGN KEY (municipality_id) REFERENCES municipalities(id) ON DELETE CASCADE,
  UNIQUE KEY uq_barangay (municipality_id, name)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS teachers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  contact_number VARCHAR(30) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  username VARCHAR(50) NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'conductor' CHECK (role IN ('admin','conductor','super_admin')),
  teacher_id INT NULL,
  photo_url VARCHAR(255) NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  -- Self-service signup gating: admin-created accounts (via Manage Users) are created
  -- already approved; only the public /auth/signup path starts as 'pending'. Email
  -- verification was dropped (would need a paid/verified sending domain) - approval alone
  -- gates login now.
  email_verified BOOLEAN NOT NULL DEFAULT true,
  email_verification_token VARCHAR(64) NULL,
  email_verification_expires DATETIME NULL,
  approval_status VARCHAR(20) NOT NULL DEFAULT 'approved' CHECK (approval_status IN ('pending','approved','rejected')),
  contact_number VARCHAR(30) NULL,
  location VARCHAR(255) NULL,
  shared_latitude DOUBLE NULL,
  shared_longitude DOUBLE NULL,
  shared_location_at DATETIME NULL,
  last_login_at DATETIME NULL,
  last_seen_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_teacher FOREIGN KEY (teacher_id) REFERENCES teachers(id) ON DELETE SET NULL,
  UNIQUE KEY uq_users_username (username)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS deaf_individuals (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uuid VARCHAR(36) NOT NULL UNIQUE,
  full_name VARCHAR(190) NOT NULL,
  photo_url VARCHAR(255) NULL,
  age INT NULL,
  birth_date DATE NULL,
  gender VARCHAR(10) NOT NULL CHECK (gender IN ('Male','Female','Other')),
  barangay_id INT NOT NULL,
  purok VARCHAR(100) NULL,
  municipality_id INT NOT NULL,
  latitude DOUBLE NULL,
  longitude DOUBLE NULL,
  skill_level VARCHAR(20) NOT NULL DEFAULT 'Natural' CHECK (skill_level IN ('Skilled','Semi-skilled','Natural')),
  monitoring_status VARCHAR(20) NOT NULL DEFAULT 'Unlocated' CHECK (monitoring_status IN ('RV','BS','Transferred','Unlocated')),
  assigned_teacher_id INT NULL,
  assigned_date DATE NULL,
  contact_number VARCHAR(30) NULL,
  email VARCHAR(190) NULL,
  marital_status VARCHAR(20) NULL CHECK (marital_status IS NULL OR marital_status IN ('Single','Married','Widowed','Separated','Divorced')),
  emergency_contact_name VARCHAR(150) NULL,
  emergency_contact_number VARCHAR(30) NULL,
  notes TEXT NULL,
  is_deleted BOOLEAN NOT NULL DEFAULT false,
  created_by INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_deaf_municipality FOREIGN KEY (municipality_id) REFERENCES municipalities(id),
  CONSTRAINT fk_deaf_barangay FOREIGN KEY (barangay_id) REFERENCES barangays(id),
  CONSTRAINT fk_deaf_teacher FOREIGN KEY (assigned_teacher_id) REFERENCES teachers(id) ON DELETE SET NULL,
  CONSTRAINT fk_deaf_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_deaf_updated_at (updated_at),
  INDEX idx_deaf_municipality (municipality_id),
  INDEX idx_deaf_name (full_name)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS visits (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uuid VARCHAR(36) NOT NULL UNIQUE,
  deaf_individual_id INT NOT NULL,
  visit_datetime DATETIME NOT NULL,
  latitude DOUBLE NULL,
  longitude DOUBLE NULL,
  conductor_id INT NULL,
  conductor_name VARCHAR(150) NULL,
  created_by INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_visit_deaf FOREIGN KEY (deaf_individual_id) REFERENCES deaf_individuals(id) ON DELETE CASCADE,
  CONSTRAINT fk_visit_teacher FOREIGN KEY (conductor_id) REFERENCES teachers(id) ON DELETE SET NULL,
  CONSTRAINT fk_visit_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_visit_deaf (deaf_individual_id),
  INDEX idx_visit_updated_at (updated_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS remarks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uuid VARCHAR(36) NOT NULL UNIQUE,
  visit_id INT NOT NULL,
  user_id INT NULL,
  user_name VARCHAR(150) NULL,
  remark_text TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_remark_visit FOREIGN KEY (visit_id) REFERENCES visits(id) ON DELETE CASCADE,
  CONSTRAINT fk_remark_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_remark_visit (visit_id),
  INDEX idx_remark_updated_at (updated_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS user_devices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  device_id VARCHAR(100) NOT NULL,
  device_label VARCHAR(150) NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('approved','pending','rejected')),
  approved_by INT NULL,
  approved_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_device_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_device_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE KEY uq_user_device (user_id, device_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS password_reset_requests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  note VARCHAR(500) NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','resolved')),
  requested_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at DATETIME NULL,
  resolved_by INT NULL,
  CONSTRAINT fk_prr_resolved_by FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_password_reset_status (status, requested_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS teacher_assignment_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  deaf_individual_id INT NOT NULL,
  old_teacher_id INT NULL,
  new_teacher_id INT NULL,
  changed_by INT NULL,
  reason VARCHAR(255) NULL,
  changed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_tah_deaf FOREIGN KEY (deaf_individual_id) REFERENCES deaf_individuals(id) ON DELETE CASCADE,
  CONSTRAINT fk_tah_old_teacher FOREIGN KEY (old_teacher_id) REFERENCES teachers(id) ON DELETE SET NULL,
  CONSTRAINT fk_tah_new_teacher FOREIGN KEY (new_teacher_id) REFERENCES teachers(id) ON DELETE SET NULL,
  CONSTRAINT fk_tah_changed_by FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_tah_deaf (deaf_individual_id, changed_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS settings (
  `key` VARCHAR(100) NOT NULL PRIMARY KEY,
  `value` VARCHAR(255) NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

INSERT IGNORE INTO settings (`key`, `value`) VALUES ('overdue_visit_days', '30');

CREATE TABLE IF NOT EXISTS calendar_events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(190) NOT NULL,
  description TEXT NULL,
  event_date DATE NOT NULL,
  created_by INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_calendar_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_calendar_events_date (event_date)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS audit_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NULL,
  action VARCHAR(50) NOT NULL,
  entity_type VARCHAR(50) NOT NULL,
  entity_id INT NULL,
  details TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Chat module: temporary, admin-scheduled group chat sessions -------------

-- A recurring template ("every Mon/Wed/Fri, 8:00-9:00 AM") that chatScheduler.js's
-- generateScheduledSessions() turns into a real chat_sessions row each day it's due, so an
-- admin/super_admin sets this up once instead of creating the same session every time.
CREATE TABLE IF NOT EXISTS chat_recurring_schedules (
  id INT AUTO_INCREMENT PRIMARY KEY,
  session_name VARCHAR(150) NOT NULL,
  description VARCHAR(500) NULL,
  -- JSON array of ints, 0=Sunday..6=Saturday (matching Postgres's EXTRACT(DOW ...)
  -- convention this project used before - see (DAYOFWEEK(x) - 1) at call sites).
  days_of_week JSON NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  retention_policy VARCHAR(20) NOT NULL DEFAULT 'immediate' CHECK (retention_policy IN ('immediate','24h','7d')),
  is_active BOOLEAN NOT NULL DEFAULT true,
  -- The Manila-local calendar date a session was last auto-generated for - prevents generating a
  -- second session for the same day if the scheduler tick runs more than once while still due.
  last_generated_date DATE NULL,
  created_by INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_crs_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- A one-off exception for a single calendar date ("just this Monday, 10 AM-4 PM instead of the
-- usual recurring window") - at most one per schedule_date (UNIQUE), and when active it takes
-- priority over whatever a recurring schedule would otherwise generate that day (see
-- chatScheduler.js::generateScheduledSessions). is_active=false means it's saved on file but
-- deliberately not in effect - the "Keep Recurring Schedule" choice when an admin's single-time
-- save conflicted with an existing recurring schedule for that weekday.
CREATE TABLE IF NOT EXISTS chat_single_schedules (
  id INT AUTO_INCREMENT PRIMARY KEY,
  session_name VARCHAR(150) NOT NULL,
  schedule_date DATE NOT NULL UNIQUE,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  remarks VARCHAR(500) NULL,
  retention_policy VARCHAR(20) NOT NULL DEFAULT 'immediate' CHECK (retention_policy IN ('immediate','24h','7d')),
  is_active BOOLEAN NOT NULL DEFAULT true,
  -- 'scheduled' until its date passes, then the scheduler flips it to 'completed' (archived, kept
  -- for audit history rather than deleted) - never 'cancelled' automatically, only via admin delete.
  status VARCHAR(20) NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled','completed','cancelled')),
  created_by INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_css_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS chat_sessions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  session_name VARCHAR(150) NOT NULL,
  description VARCHAR(500) NULL,
  start_datetime DATETIME NOT NULL,
  end_datetime DATETIME NOT NULL,
  -- 'scheduled' (before start) -> 'open' (auto, at start time, or admin can open early) ->
  -- 'closed' (admin closed early - can be re-opened while still before end_datetime) ->
  -- 'expired' (auto, at end time or admin delete-via-expiry - terminal, chatScheduler.js cleans up).
  status VARCHAR(20) NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled','open','closed','expired')),
  -- How long expired messages are kept before chatScheduler.js purges them - 'immediate' means
  -- deleted the moment the session expires, matching the primary spec; 24h/7d is the "recommended
  -- enhancement" retention window, admin-configurable per session at creation time.
  retention_policy VARCHAR(20) NOT NULL DEFAULT 'immediate' CHECK (retention_policy IN ('immediate','24h','7d')),
  five_min_warning_sent BOOLEAN NOT NULL DEFAULT false,
  expired_at DATETIME NULL,
  purge_at DATETIME NULL,
  messages_purged BOOLEAN NOT NULL DEFAULT false,
  created_by INT NULL,
  -- Set only for sessions the scheduler auto-generated from a recurring schedule - null for
  -- one-off sessions an admin created directly. ON DELETE SET NULL so deleting the recurring
  -- schedule later doesn't retroactively orphan/delete sessions it already generated.
  recurring_schedule_id INT NULL,
  -- Set only for sessions generated from a single-time schedule - mutually exclusive with
  -- recurring_schedule_id in practice (the scheduler never generates both for the same day).
  single_schedule_id INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_cs_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_cs_recurring_schedule FOREIGN KEY (recurring_schedule_id) REFERENCES chat_recurring_schedules(id) ON DELETE SET NULL,
  CONSTRAINT fk_cs_single_schedule FOREIGN KEY (single_schedule_id) REFERENCES chat_single_schedules(id) ON DELETE SET NULL,
  INDEX idx_chat_sessions_status (status, end_datetime)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS chat_messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  session_id INT NOT NULL,
  user_id INT NOT NULL,
  message VARCHAR(2000) NOT NULL,
  sent_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  edited_at DATETIME NULL,
  is_deleted BOOLEAN NOT NULL DEFAULT false,
  is_pinned BOOLEAN NOT NULL DEFAULT false,
  CONSTRAINT fk_cm_session FOREIGN KEY (session_id) REFERENCES chat_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_cm_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_chat_messages_session (session_id, id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS chat_participants (
  id INT AUTO_INCREMENT PRIMARY KEY,
  session_id INT NOT NULL,
  user_id INT NOT NULL,
  joined_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  left_at DATETIME NULL,
  -- Refreshed by the app's periodic heartbeat while the Chat Room screen is open - drives the
  -- Online/Offline status shown in the participant list (see chat.controller.js::listParticipants).
  last_active_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_muted BOOLEAN NOT NULL DEFAULT false,
  is_removed BOOLEAN NOT NULL DEFAULT false,
  CONSTRAINT fk_cp_session FOREIGN KEY (session_id) REFERENCES chat_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_cp_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE KEY uq_chat_participant (session_id, user_id),
  INDEX idx_chat_participants_session (session_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS chat_notifications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  session_id INT NULL,
  message VARCHAR(255) NOT NULL,
  sent_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(20) NOT NULL DEFAULT 'unread' CHECK (status IN ('unread','read')),
  CONSTRAINT fk_cn_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_cn_session FOREIGN KEY (session_id) REFERENCES chat_sessions(id) ON DELETE CASCADE,
  INDEX idx_chat_notifications_user (user_id, status)
) ENGINE=InnoDB;
