-- Deaf Registry and Monitoring System - PostgreSQL (Supabase) schema
-- Translated from the original MySQL schema.sql. Key differences from that version:
--   * id columns use GENERATED BY DEFAULT AS IDENTITY (not ALWAYS) so the one-off
--     data migration script can insert explicit legacy ids from the MySQL database.
--   * ENUM columns become VARCHAR + CHECK constraints (easier to alter later than
--     native Postgres enum types — this project has already extended enum-like
--     columns, e.g. marital_status, more than once).
--   * TINYINT(1) booleans become native BOOLEAN.
--   * DATETIME becomes TIMESTAMP.
--   * MySQL's "ON UPDATE CURRENT_TIMESTAMP" has no direct equivalent — handled via
--     a shared trigger function (set_updated_at) applied per table below.

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS municipalities (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DROP TRIGGER IF EXISTS trg_municipalities_updated_at ON municipalities;
CREATE TRIGGER trg_municipalities_updated_at BEFORE UPDATE ON municipalities
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS barangays (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  municipality_id INT NOT NULL REFERENCES municipalities(id) ON DELETE CASCADE,
  name VARCHAR(150) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_barangay UNIQUE (municipality_id, name)
);
DROP TRIGGER IF EXISTS trg_barangays_updated_at ON barangays;
CREATE TRIGGER trg_barangays_updated_at BEFORE UPDATE ON barangays
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS teachers (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  contact_number VARCHAR(30) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DROP TRIGGER IF EXISTS trg_teachers_updated_at ON teachers;
CREATE TRIGGER trg_teachers_updated_at BEFORE UPDATE ON teachers
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'conductor' CHECK (role IN ('admin','conductor')),
  teacher_id INT NULL REFERENCES teachers(id) ON DELETE SET NULL,
  photo_url VARCHAR(255) NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  -- Self-service signup gating: admin-created accounts (via Manage Users) are created
  -- already verified+approved; only the public /auth/signup path starts these false/pending.
  email_verified BOOLEAN NOT NULL DEFAULT true,
  email_verification_token VARCHAR(64) NULL,
  email_verification_expires TIMESTAMP NULL,
  approval_status VARCHAR(20) NOT NULL DEFAULT 'approved' CHECK (approval_status IN ('pending','approved','rejected')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS deaf_individuals (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid VARCHAR(36) NOT NULL UNIQUE,
  full_name VARCHAR(190) NOT NULL,
  photo_url VARCHAR(255) NULL,
  age INT NULL,
  birth_date DATE NULL,
  gender VARCHAR(10) NOT NULL CHECK (gender IN ('Male','Female','Other')),
  barangay_id INT NOT NULL REFERENCES barangays(id),
  purok VARCHAR(100) NULL,
  municipality_id INT NOT NULL REFERENCES municipalities(id),
  latitude DOUBLE PRECISION NULL,
  longitude DOUBLE PRECISION NULL,
  skill_level VARCHAR(20) NOT NULL DEFAULT 'Natural' CHECK (skill_level IN ('Skilled','Semi-skilled','Natural')),
  monitoring_status VARCHAR(20) NOT NULL DEFAULT 'Unlocated' CHECK (monitoring_status IN ('RV','BS','Transferred','Unlocated')),
  assigned_teacher_id INT NULL REFERENCES teachers(id) ON DELETE SET NULL,
  assigned_date DATE NULL,
  contact_number VARCHAR(30) NULL,
  email VARCHAR(190) NULL,
  marital_status VARCHAR(20) NULL CHECK (marital_status IS NULL OR marital_status IN ('Single','Married','Widowed','Separated','Divorced')),
  emergency_contact_name VARCHAR(150) NULL,
  emergency_contact_number VARCHAR(30) NULL,
  notes TEXT NULL,
  is_deleted BOOLEAN NOT NULL DEFAULT false,
  created_by INT NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DROP TRIGGER IF EXISTS trg_deaf_individuals_updated_at ON deaf_individuals;
CREATE TRIGGER trg_deaf_individuals_updated_at BEFORE UPDATE ON deaf_individuals
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX IF NOT EXISTS idx_deaf_updated_at ON deaf_individuals (updated_at);
CREATE INDEX IF NOT EXISTS idx_deaf_municipality ON deaf_individuals (municipality_id);
CREATE INDEX IF NOT EXISTS idx_deaf_name ON deaf_individuals (full_name);

CREATE TABLE IF NOT EXISTS visits (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid VARCHAR(36) NOT NULL UNIQUE,
  deaf_individual_id INT NOT NULL REFERENCES deaf_individuals(id) ON DELETE CASCADE,
  visit_datetime TIMESTAMP NOT NULL,
  latitude DOUBLE PRECISION NULL,
  longitude DOUBLE PRECISION NULL,
  conductor_id INT NULL REFERENCES teachers(id) ON DELETE SET NULL,
  conductor_name VARCHAR(150) NULL,
  created_by INT NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DROP TRIGGER IF EXISTS trg_visits_updated_at ON visits;
CREATE TRIGGER trg_visits_updated_at BEFORE UPDATE ON visits
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX IF NOT EXISTS idx_visit_deaf ON visits (deaf_individual_id);
CREATE INDEX IF NOT EXISTS idx_visit_updated_at ON visits (updated_at);

CREATE TABLE IF NOT EXISTS remarks (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid VARCHAR(36) NOT NULL UNIQUE,
  visit_id INT NOT NULL REFERENCES visits(id) ON DELETE CASCADE,
  user_id INT NULL REFERENCES users(id) ON DELETE SET NULL,
  user_name VARCHAR(150) NULL,
  remark_text TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DROP TRIGGER IF EXISTS trg_remarks_updated_at ON remarks;
CREATE TRIGGER trg_remarks_updated_at BEFORE UPDATE ON remarks
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX IF NOT EXISTS idx_remark_visit ON remarks (visit_id);
CREATE INDEX IF NOT EXISTS idx_remark_updated_at ON remarks (updated_at);

CREATE TABLE IF NOT EXISTS user_devices (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_id VARCHAR(100) NOT NULL,
  device_label VARCHAR(150) NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('approved','pending','rejected')),
  approved_by INT NULL REFERENCES users(id) ON DELETE SET NULL,
  approved_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_user_device UNIQUE (user_id, device_id)
);

CREATE TABLE IF NOT EXISTS teacher_assignment_history (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deaf_individual_id INT NOT NULL REFERENCES deaf_individuals(id) ON DELETE CASCADE,
  old_teacher_id INT NULL REFERENCES teachers(id) ON DELETE SET NULL,
  new_teacher_id INT NULL REFERENCES teachers(id) ON DELETE SET NULL,
  changed_by INT NULL REFERENCES users(id) ON DELETE SET NULL,
  reason VARCHAR(255) NULL,
  changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_tah_deaf ON teacher_assignment_history (deaf_individual_id, changed_at);

CREATE TABLE IF NOT EXISTS settings (
  "key" VARCHAR(100) NOT NULL PRIMARY KEY,
  "value" VARCHAR(255) NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DROP TRIGGER IF EXISTS trg_settings_updated_at ON settings;
CREATE TRIGGER trg_settings_updated_at BEFORE UPDATE ON settings
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

INSERT INTO settings ("key", "value") VALUES ('overdue_visit_days', '30')
  ON CONFLICT ("key") DO NOTHING;

CREATE TABLE IF NOT EXISTS audit_logs (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT NULL REFERENCES users(id) ON DELETE SET NULL,
  action VARCHAR(50) NOT NULL,
  entity_type VARCHAR(50) NOT NULL,
  entity_id INT NULL,
  details TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
